### ISSUE TITLE
Public Release

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/glassfish-grizzly#2035]
Last CTS runs indicate no failures in this component. It's time to make a public release. Before the release make sure that Eclipse Release Review is passed and all dependencies have been released.

**Comment by anajosep** [comment]
Released Grizzly Artifacts part of the Grizzly Project 2.4.4 to maven central
https://ci.eclipse.org/grizzly/job/Grizzly-maven-central-release/11/console

Awaiting the sync so that the repository is made available in Maven central. I would close this issue once its made available in Maven central.

Last few lines from the job.
[INFO] --- nexus-staging-maven-plugin:1.6.8:rc-release (default-cli) @ grizzly-project ---
[INFO]  + Using server credentials "ossrh" from Maven settings.
[INFO]  * Connected to Nexus at https://oss.sonatype.org:443/, is version 2.14.11-01 and edition "Professional"

[INFO] RC-Releasing staging repository with IDs=[orgglassfishgrizzly-1025]

Waiting for operation to complete...
....................

[INFO] Released

**Comment by anajosep** [comment]
The grizzly repos are available in Maven Central.
http://central.maven.org/maven2/org/glassfish/grizzly/grizzly-project/2.4.4/
http://central.maven.org/maven2/org/glassfish/grizzly/grizzly-core/2.4.4/

**Comment by anajosep** [comment]
Released Grizzly BOM project to Maven central using the below job.
https://ci.eclipse.org/grizzly/job/Grizzly-maven-central-release/12/console

Awaiting the sync so that the repository is made available in Maven central. I would close this issue once its made available in Maven central.

Last few lines from the job.

INFO] --- nexus-staging-maven-plugin:1.6.8:rc-release (default-cli) @ grizzly-project ---
[INFO]  + Using server credentials "ossrh" from Maven settings.
[INFO]  * Connected to Nexus at https://oss.sonatype.org:443/, is version 2.14.11-01 and edition "Professional"

Waiting for operation to complete...
....................

[INFO] Released

**Comment by anajosep** [comment]
Released Grizzly BOM project to Maven central using the below job.
https://ci.eclipse.org/grizzly/job/Grizzly-maven-central-release/12/console

Awaiting the sync so that the repository is made available in Maven central. I would close this issue once its made available in Maven central.

Last few lines from the job.

INFO] --- nexus-staging-maven-plugin:1.6.8:rc-release (default-cli) @ grizzly-project ---
[INFO]  + Using server credentials "ossrh" from Maven settings.
[INFO]  * Connected to Nexus at https://oss.sonatype.org:443/, is version 2.14.11-01 and edition "Professional"

Waiting for operation to complete...
....................

[INFO] Released

**Comment by anajosep** [comment]
grizzly-bom:2.4.4 is released to Maven central and its available here.
http://central.maven.org/maven2/org/glassfish/grizzly/grizzly-bom/2.4.4/

Closing this issue as all artifacts required for building GlassFish is released.
