### ISSUE TITLE
Readme Claims JDK 1.8 is needed But Build Requires JDK 1.9

### ISSUE THREAD

**Issue by brintoul** [eclipse-ee4j/glassfish-grizzly#2056]
JDK requirements do not mention the need for JDK 1.9

**Comment by smillidge** [comment]
I don't understand the issue raised. Grizzly doesn't need JDK 1.9?

**Comment by brintoul** [comment]
In building Grizzly, I get the following warning (which I believe leads to an error):

[INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-versions) @ grizzly-project ---
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.RequireJavaVersion failed with message:
You need JDK 1.9 and above to compile Grizzly! JDK 1.7 could be still used at runtime

Is this something I should change in my local file?
https://github.com/eclipse-ee4j/grizzly/blob/master/pom.xml#L505

**Comment by bshannon** [comment]
Looks like the README wasn't updated.

When trying to build with JDK 1.8 some tests fail for me in the http-servlet module.
Even building with JDK 9 fails for me, so something else is wrong, at least for me.
I've assigned this to @ankitoracle who might be able to help determine why JDK 9+
is now required and/or whether the README should be updated.

**Comment by ankitoracle** [comment]
I tried mvn clean install as mentioned in the README. The build fails with JDK 8.Using jdk 9.0.4 and Apache Maven 3.0.5,the build seems to have run fine.The report shows Tests run: 129, Failures: 0, Errors: 1, Skipped: 0 The README needs to be updated to reflect the required JAVA version

I am looking into the Test which had an error due to BindException.

java.net.BindException: Address already in use: bind
        at org.glassfish.grizzly.http.HttpSemanticsTest.doTest(HttpSemanticsTest
.java:897)
        at org.glassfish.grizzly.http.HttpSemanticsTest.doTest(HttpSemanticsTest
.java:881)
        at org.glassfish.grizzly.http.HttpSemanticsTest.testHttpGetWithPayloadEn
abled(HttpSemanticsTest.java:523)

**Comment by brintoul** [comment]
The README does state "Apache Maven 3.3.9 or later in order to build and run the tests." - not sure if that's a factor in your failing test...
